[build]
  command = "npm i && cd api && npm i && cd ../web-react-ts && npm i && cd .. && npm run build  && cp -r api/build/schema api/build/functions/graphql/. && cd api/src/functions/graphql && npm i"
  publish = "web-react-ts/dist"
  functions = "api/build/functions"

[dev]
  command = "npm start"

[context.production]
  command = "npm run doppler-install && npm i && cd api && npm i && cd ../web-react-ts && npm i && cd .. && ./doppler setup --no-interactive --token $DOPPLER_TOKEN_PRD && ./doppler run --token $DOPPLER_TOKEN_PRD --command='npm run build  && cp -r api/build/schema api/build/functions/graphql/. && cd api/src/functions/graphql && npm i'"

[context.deploy-preview]
  command = "npm run doppler-install && npm i && cd api && npm i && cd ../web-react-ts && npm i && cd .. && ./doppler setup --no-interactive --token $DOPPLER_TOKEN_STG && ./doppler run --token $DOPPLER_TOKEN_STG --command='npm run build  && cp -r api/build/schema api/build/functions/graphql/. && cd api/src/functions/graphql && npm i'"


[template.environment]
  NEO4J_URI = "Neo4j URI (ex: bolt://localhost:7687)"
  NEO4J_USER = "Neo4j User"
  NEO4J_PASSWORD = "Neo4j Password"
  
[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200